import random

objects = [
    "Astronaut",
    "Ballerina",
    "Baseball",
    "Basketball",
    "Bee",
    "Bird",
    "Bus driver",
    "Carpenter",
    "Cat",
    "Cheerleader",
    "Chef",
    "Chicken",
    "Clown",
    "Cow",
    "Cowboy",
    "Dancer",
    "Dentist",
    "Detective",
    "Doctor",
    "Dog",
    "Dragon",
    "Elephant",
    "Elf",
    "Farmer",
    "Firefighter",
    "Fisherman",
    "Football player",
    "Frog",
    "Ghost",
    "Golfer",
    "Horse",
    "Jockey",
    "Judge",
    "King",
    "Knight",
    "Lion",
    "Magician",
    "Mailman",
    "Mermaid",
    "Mime",
    "Monkey",
    "Monster",
    "Nurse",
    "Pilot",
    "Pirate",
    "Police officer",
    "Prince",
    "Princess",
    "Rabbit",
    "Racer",
    "Referee",
    "Robot",
    "Rock star",
    "Santa Claus",
    "Scarecrow",
    "Scientist",
    "Shepherd",
    "Singer",
    "Skater",
    "Soldier",
    "Superhero",
    "Surgeon",
    "Teacher",
    "Tiger",
    "Tooth fairy",
    "Train conductor",
    "Unicorn",
    "Vampire",
    "Waiter",
    "Witch",
    "Wizard",
    "Wolf",
    "Zombie",
]

#  shuffle them
random.shuffle(objects)
