POST https://models.inference.ai.azure.com/chat/completions
Authorization: Bearer {{$dotenv TOKEN}}
Content-Type: application/json

{
    "model": "meta-llama-3-8b-instruct",
    "messages": [{"role":"system","content":"You are an improv club member playing improv games."},
                 {"role":"user","content":"Suggest a random first line for a scene."}],
    "max_tokens": 800,
    "temperature": 0.7,
    "frequency_penalty": 0,
    "presence_penalty": 0,
    "top_p": 0.95,
    "stop": null
}
